name: "aryanfront"
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  meta: ^1.16.0
  provider: ^6.1.5+1
  json_annotation: ^4.9.0
  share_plus: ^12.0.1
  http: ^1.5.0
  sqflite: ^2.4.0
  path: ^1.8.3
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2
  persistent_bottom_nav_bar: ^6.2.1
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_otp_text_field: ^1.5.1+1
  get_it: ^9.0.5
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.1
  build_runner: ^2.10.1
  json_serializable: ^6.11.1

dependency_overrides:
  source_gen: ^4.0.2
  http:
    hosted:
      name: http
      url: https://pub.flutter-io.cn

flutter:
  fonts:
    - family: IRANSansX
      fonts:
        - asset: assets/fonts/IRANSansX-Regular.ttf
        - asset: assets/fonts/IRANSansX-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 600

    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan.ttf
  assets:
    - assets/images/account.png
    - assets/images/activeaccount.png
    - assets/images/defaults.png
    - assets/images/activedefaults.png
    - assets/images/menu.png
    - assets/images/activemenu.png
    - assets/images/new.png
    - assets/images/activenew.png
    - assets/images/opened.png
    - assets/images/activeopened.png
    - assets/images/userinfo.png
    - assets/images/user_devices.png
    - assets/images/user_sign_out.png
    - assets/images/user_title.png
    - assets/images/user_other_accounts.png
    - assets/images/user_settings.png
    - assets/images/user_wallet.png
    - assets/images/user_password_change.png
    - assets/images/sort.png
    - assets/images/filternone.png
    - assets/images/filtersigning.png
    - assets/images/refresh.png
    - assets/images/futures.png
    - assets/images/more.png
    - assets/images/pagination_right.png
    - assets/images/pagination_left.png
    - assets/images/add.png
    - assets/images/aryan_app.png
    - assets/images/lang_icon.png
    - assets/images/eyes_close.png
    - assets/images/eyes_open.png

  generate: true
  uses-material-design: true



event_data:
  { }

event_id:
  - 
